name: Update README

on:
  push:
    branches:
      - master  # Modify this if your default branch has a different name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can choose the Node.js version you prefer.

    - name: Install dependencies
      run: npm install

    - name: Run script to update README
      run: node scripts/update_readme.js

    - name: Commit and push if README changed
      run: |
        git config --local user.email "bot@arjunkrishna.in"
        git config --local user.name "Cipher Bot"

        # Set the bot's Personal Access Token as an environment variable
        export GH_TOKEN="${{ secrets.BOT_ACCESS_TOKEN }}"

        # Push the changes
        git add README.md
        git commit -m "Update README using GitHub Action"
        git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
      if: github.event_name == 'push'
      env:
        GH_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
